// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJo8YqaocS2vdAgwCT6laDQligZFZLtQ',
    appId: '1:770292188735:web:825205095b408d09a51a8a',
    messagingSenderId: '770292188735',
    projectId: 'bloodconnect-mvp-b605f',
    authDomain: 'bloodconnect-mvp-b605f.firebaseapp.com',
    storageBucket: 'bloodconnect-mvp-b605f.firebasestorage.app',
    measurementId: 'G-BT6L5T8PRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIcrYZ-9MCgRaDBSxExRYuOEz41s82dAI',
    appId: '1:770292188735:android:68667982e9605683a51a8a',
    messagingSenderId: '770292188735',
    projectId: 'bloodconnect-mvp-b605f',
    storageBucket: 'bloodconnect-mvp-b605f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAX3lZ_0zN13UF4JA8G30_VBek8I8sbEI',
    appId: '1:770292188735:ios:c4d3269a7088ad73a51a8a',
    messagingSenderId: '770292188735',
    projectId: 'bloodconnect-mvp-b605f',
    storageBucket: 'bloodconnect-mvp-b605f.firebasestorage.app',
    iosClientId: '770292188735-5pl1j2je8fvb4j6m8v72ic6qag0h42gv.apps.googleusercontent.com',
    iosBundleId: 'com.bloodconnect.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAX3lZ_0zN13UF4JA8G30_VBek8I8sbEI',
    appId: '1:770292188735:ios:c4d3269a7088ad73a51a8a',
    messagingSenderId: '770292188735',
    projectId: 'bloodconnect-mvp-b605f',
    storageBucket: 'bloodconnect-mvp-b605f.firebasestorage.app',
    iosClientId: '770292188735-5pl1j2je8fvb4j6m8v72ic6qag0h42gv.apps.googleusercontent.com',
    iosBundleId: 'com.bloodconnect.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGJo8YqaocS2vdAgwCT6laDQligZFZLtQ',
    appId: '1:770292188735:web:9470cdad68ab1a44a51a8a',
    messagingSenderId: '770292188735',
    projectId: 'bloodconnect-mvp-b605f',
    authDomain: 'bloodconnect-mvp-b605f.firebaseapp.com',
    storageBucket: 'bloodconnect-mvp-b605f.firebasestorage.app',
    measurementId: 'G-LPK4TBLH6L',
  );
}
